//
// Created by louis on 22/09/2023.
// contains defines
//

#ifndef DOOM_DEFINES_H
#define DOOM_DEFINES_H

#define NB_MONSTER_TYPE 4
#define NBMONSTERS_MAX 3
#define NBMONSTERS_MIN 2
#define MONSTER_MAX_PV 80
#define MONSTER_MIN_PV 40
#define MONSTER_MAX_DEFENSE 10
#define MONSTER_MIN_DEFENSE 4
#define MAX_GOLD_LOOT 20
#define MIN_GOLD_LOOT 5
#define MIN_MONSTER_XP 20
#define MAX_MONSTER_XP 50

#define MIN_MONSTER_XP 20
#define MAX_MONSTER_XP 50

#define MIN_BOSS_XP 300
#define MAX_BOSS_XP 500
#define NB_BOSS_TYPE 2
#define BOSS_MAX_PV 200
#define BOSS_MIN_PV 160
#define BOSS_MAX_DEFENSE 15
#define BOSS_MIN_DEFENSE 10
#define MAX_BOSS_GOLD_LOOT 20
#define MIN_BOSS_GOLD_LOOT 5
#define VALUE_SPELL_MAX 10
#define SPELL_COST_MAX 25
#define NB_SPELL_TYPE 4



#define NBLEVELS 5

#define MAX_LEVEL_LOOT_ITEM 10

#define NBOBJECTS_MAX 10
#define NBSPELL_MAX 3

#define NB_PLAYER_LEVELS 50

#endif //DOOM_DEFINES_H
