//
// Created by louis on 05/11/2023.
//

#ifndef DOOM_QUESTS_DEFINES_H
#define DOOM_QUESTS_DEFINES_H

#define KILL_10_MONSTERS 1
#define REACH_SECOND_LEVEL 2
#define FINISH_TWO_QUESTS 3

#endif //DOOM_QUESTS_DEFINES_H
